### ISSUE TITLE
raml2html branch 1.0 not working with node 0.12

### ISSUE THREAD

**Issue by alfrescian** [raml2html/raml2html#209]
Hi,

I've created a demo project here: [raml2html-demo](https://github.com/alfrescian/raml2html-demo) that just uses the 1.0 branch & runs the html generation for the included raml1.0/example.raml
It runs successful on node 5 but it fails on node 0.12:
```
[Error: Template render error: (/home/travis/build/alfrescian/raml2html-demo/node_modules/raml2html/lib/template.nunjucks)
  Template render error: (/home/travis/build/alfrescian/raml2html-demo/node_modules/raml2html/lib/resource.nunjucks) [Line 134, Column 51]
  TypeError: undefined is not a function]
```

I've created a travis config for node 5 & 0.12: https://travis-ci.org/alfrescian/raml2html-demo

**Comment by kevinrenskers** [comment]
You need Node 4 or higher.
